from pydantic import BaseModel, Field

class LLMVerificationRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=3,
        max_length=2000,
        description="The question posed to the LLM."
    )
    answer: str = Field(
        ...,
        min_length=3,
        max_length=8000,
        description="The answer generated by the LLM."
    )

    class Config:
        extra = "forbid"
        str_strip_whitespace = True