from pydantic import BaseModel, Field
from typing import Literal

class LLMVerificationRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=3,
        max_length=2000,
        description="The question posed to the LLM."
    )
    answer: str = Field(
        ...,
        min_length=3,
        max_length=8000,
        description="The answer generated by the LLM."
    )
    mode: Literal["fast", "full"] = Field(
        "full", 
        description="The verification mode to use. 'fast' for speed, 'full' for depth."
    )

    class Config:
        extra = "forbid"
        str_strip_whitespace = True